export const ADD_TODO = 'ADD_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const SET_CURRENT_TODO = 'SET_CURRENT_TODO';
export const CLEAR_CURRENT_TODO = 'CLEAR_CURRENT_TODO';
export const UPDATE_TODO = 'UPDATE_TODO';
export const FILTER_TODOS = 'FILTER_TODOS';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const TOGGLE_COMPLETED = 'TOGGLE_COMPLETED';
